steps:
  # Download cargo registry cache from GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Downloading cargo cache..."
        gsutil -m cp gs://${PROJECT_ID}_cloudbuild_cache/cargo-cache.tar.gz cargo-cache.tar.gz 2>/dev/null || echo "No cache found"
        if [ -f cargo-cache.tar.gz ]; then
          tar -xzf cargo-cache.tar.gz
          echo "Cache restored"
        fi
    volumes:
      - name: 'cargo-cache'
        path: '/workspace/.cargo'

  # Pull previous image for Docker layer caching
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/io7-backend:latest || exit 0']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/io7-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/io7-backend:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/io7-backend:latest'
      - '--build-arg'
      - 'CARGO_HOME=/workspace/.cargo'
      - '.'
    volumes:
      - name: 'cargo-cache'
        path: '/workspace/.cargo'

  # Save cargo cache back to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Saving cargo cache..."
        tar -czf cargo-cache.tar.gz .cargo/registry .cargo/git 2>/dev/null || true
        gsutil -m cp cargo-cache.tar.gz gs://${PROJECT_ID}_cloudbuild_cache/cargo-cache.tar.gz || true
    volumes:
      - name: 'cargo-cache'
        path: '/workspace/.cargo'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/io7-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'io7-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/io7-backend:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  timeout: '1200s'

substitutions:
  _DEPLOY_REGION: us-central1