name: Agent Idea
description: Suggest an agent you'd like to see in io7
title: "[Request Subagent] "
labels: ["request-subagent"]
body:
  - type: markdown
    attributes:
      value: |
        ## Suggest a Subagent
        
        Have an idea for an agent that would be useful? Let us know!
        
  - type: textarea
    id: agent-idea
    attributes:
      label: Subagent Idea
      description: Describe the agent you'd like to see. Be as detailed or brief as you want!
      placeholder: |
        I'd love an agent that could help with database migrations. It could analyze the current schema, suggest migration strategies, and write the migration scripts...
        
        Or simply: "An agent that converts CSS to Tailwind"
    validations:
      required: true
      
  - type: input
    id: suggested-name
    attributes:
      label: Suggested Name (Optional)
      description: Got a name idea for this agent?
      placeholder: "e.g., database-migration-helper"
    validations:
      required: false
